"""
ICHNOS — Monte Carlo propagation of Kd uncertainty.

The structural prior is based on the two independent TIP/TetR-dimer
interfaces represented in the experimental 2NS8 structure.

Two uncertainty components are propagated:

1. structural/interface variation;
2. PRODIGY calibration uncertainty.

The resulting Kd samples are propagated through the deterministic
Kd-response curves generated by run_kd_extended.py.

Important
---------
A low ratio_spread alone does NOT imply a functional timer. At very weak
binding the circuit may simply stop responding. Therefore the relevant
criterion is the joint event:

    detectable signal AND acceptable ratio spread.

This script also:

* reports the functional Kd interval for each circuit variant;
* checks how many Monte Carlo samples lie outside the deterministic Kd grid;
* avoids silently interpreting a functional-window boundary as a required
  affinity improvement.

Usage
-----
    python kd_montecarlo.py

    python kd_montecarlo.py \
        --fold 1.5 \
        --ratio 0.05 \
        --n 200000
"""

import argparse
import csv
import math
import os

import numpy as np

from kd_config import (
    FOLD_THRESHOLD_DEFAULT,
    PRODIGY_SIGMA_KCAL_MOL,
    RATIO_THRESHOLD_DEFAULT,
    RT_KCAL_MOL,
    STRUCTURAL_DG_KCAL_MOL,
)


_HERE = os.path.dirname(os.path.abspath(__file__))

CSV_PATH = os.path.join(
    _HERE,
    "..",
    "results",
    "kd_extended.csv",
)

OUT_CSV = os.path.join(
    _HERE,
    "..",
    "results",
    "kd_montecarlo_summary.csv",
)


# -------------------------------------------------------------------------
# Thermodynamics
# -------------------------------------------------------------------------

def dg_to_kd_nM(dg):
    """
    Convert ΔG (kcal/mol) to Kd (nM).

        ΔG = RT ln(Kd)

    The exponential gives Kd in molar units; multiply by 1e9 to obtain nM.
    """

    return (
        np.exp(
            np.asarray(dg) / RT_KCAL_MOL
        )
        * 1e9
    )


# -------------------------------------------------------------------------
# Deterministic response curves
# -------------------------------------------------------------------------

def load_curves(
    path,
    readout="3h",
    scenario="frozen",
):
    """
    Return deterministic Kd-response curves:

        {
            variant:
                (
                    kd_array,
                    fold_array,
                    ratio_array
                )
        }

    Curves are sorted by Kd.

    The scenario argument prepares the analysis for the later
    physics-informed extension while retaining frozen behaviour now.
    """

    with open(
        path,
        encoding="utf-8",
    ) as fh:
        rows = list(csv.DictReader(fh))

    out = {}

    for variant in ("ox", "er"):

        pts = []

        for row in rows:

            if row["variant"] != variant:
                continue

            # Backwards compatibility with CSV files generated before
            # the scenario column was introduced.
            row_scenario = row.get(
                "scenario",
                "frozen",
            )

            if row_scenario != scenario:
                continue

            pts.append(
                (
                    float(row["kd_nM"]),
                    float(row[f"fold@{readout}"]),
                    float(
                        row[
                            f"ratio_spread@{readout}"
                        ]
                    ),
                )
            )

        pts.sort(
            key=lambda x: x[0]
        )

        if not pts:
            raise RuntimeError(
                f"No response curve found for "
                f"variant={variant}, "
                f"scenario={scenario}."
            )

        kd = np.array(
            [point[0] for point in pts],
            dtype=float,
        )

        fold = np.array(
            [point[1] for point in pts],
            dtype=float,
        )

        ratio = np.array(
            [point[2] for point in pts],
            dtype=float,
        )

        out[variant] = (
            kd,
            fold,
            ratio,
        )

    return out


def interp_log(
    kd_query,
    kd_grid,
    values,
):
    """
    Interpolate response values linearly in log(Kd).

    The deterministic grid spans several orders of magnitude, therefore
    interpolation in log(Kd) is more appropriate than interpolation
    directly in Kd.

    IMPORTANT:
    np.interp clips values outside the interpolation domain to the edge
    values. Therefore the caller must separately quantify samples that
    fall outside the deterministic Kd grid.
    """

    kd_query = np.asarray(
        kd_query,
        dtype=float,
    )

    return np.interp(
        np.log(kd_query),
        np.log(kd_grid),
        values,
    )


# -------------------------------------------------------------------------
# Functional-window calculation
# -------------------------------------------------------------------------

def find_functional_intervals(
    kd_grid,
    fold_grid,
    ratio_grid,
    fold_threshold,
    ratio_threshold,
    n_search=20000,
):
    """
    Determine contiguous Kd intervals satisfying BOTH:

        fold >= fold_threshold
        ratio <= ratio_threshold

    A dense logarithmic search is used on the interpolated deterministic
    curves.

    Returns
    -------
    intervals : list of (lower_Kd, upper_Kd)

        Bounds are in nM.

        If functionality extends to the minimum or maximum simulated Kd,
        the corresponding grid boundary is returned. This means that such
        a boundary is simulation-limited rather than necessarily a true
        biological threshold.
    """

    search_kd = np.logspace(
        np.log10(kd_grid.min()),
        np.log10(kd_grid.max()),
        n_search,
    )

    fold_search = interp_log(
        search_kd,
        kd_grid,
        fold_grid,
    )

    ratio_search = interp_log(
        search_kd,
        kd_grid,
        ratio_grid,
    )

    functional = (
        (fold_search >= fold_threshold)
        &
        (ratio_search <= ratio_threshold)
    )

    intervals = []

    if not np.any(functional):
        return intervals

    indices = np.flatnonzero(
        functional
    )

    start = indices[0]
    previous = indices[0]

    for index in indices[1:]:

        if index != previous + 1:

            intervals.append(
                (
                    float(search_kd[start]),
                    float(search_kd[previous]),
                )
            )

            start = index

        previous = index

    intervals.append(
        (
            float(search_kd[start]),
            float(search_kd[previous]),
        )
    )

    return intervals


def format_interval(
    lower,
    upper,
    grid_min,
    grid_max,
):
    """
    Human-readable functional interval.

    Marks a bound as grid-limited when functionality reaches the edge
    of the deterministic simulation domain.
    """

    tol = 1e-6

    lower_limited = (
        abs(lower - grid_min)
        <= tol * max(1.0, grid_min)
    )

    upper_limited = (
        abs(upper - grid_max)
        <= tol * max(1.0, grid_max)
    )

    if lower_limited and upper_limited:
        return (
            f"{grid_min:.4g} – {grid_max:.4g} nM "
            "(functional across entire simulated grid)"
        )

    if lower_limited:
        return (
            f"Kd <= {upper:.3f} nM "
            f"(lower side extends to simulated minimum "
            f"{grid_min:.4g} nM)"
        )

    if upper_limited:
        return (
            f"Kd >= {lower:.3f} nM "
            f"(upper side extends to simulated maximum "
            f"{grid_max:.4g} nM)"
        )

    return (
        f"{lower:.3f} – {upper:.3f} nM"
    )


# -------------------------------------------------------------------------
# Main
# -------------------------------------------------------------------------

def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--fold",
        type=float,
        default=FOLD_THRESHOLD_DEFAULT,
        help=(
            "minimum detectable fold-change "
            f"(default {FOLD_THRESHOLD_DEFAULT})"
        ),
    )

    parser.add_argument(
        "--ratio",
        type=float,
        default=RATIO_THRESHOLD_DEFAULT,
        help=(
            "maximum permitted ratio spread "
            f"(default {RATIO_THRESHOLD_DEFAULT})"
        ),
    )

    parser.add_argument(
        "--sigma",
        type=float,
        default=PRODIGY_SIGMA_KCAL_MOL,
        help=(
            "PRODIGY calibration uncertainty "
            "in kcal/mol "
            f"(default {PRODIGY_SIGMA_KCAL_MOL})"
        ),
    )

    parser.add_argument(
        "--n",
        type=int,
        default=200000,
        help="number of Monte Carlo samples",
    )

    parser.add_argument(
        "--readout",
        default="3h",
    )

    parser.add_argument(
        "--seed",
        type=int,
        default=0,
    )

    parser.add_argument(
        "--scenario",
        default="frozen",
        help=(
            "response-curve scenario "
            "(currently: frozen)"
        ),
    )

    args = parser.parse_args()

    if args.n <= 0:
        raise ValueError(
            "--n must be greater than zero."
        )

    if args.sigma < 0:
        raise ValueError(
            "--sigma must be non-negative."
        )

    rng = np.random.default_rng(
        args.seed
    )

    curves = load_curves(
        CSV_PATH,
        readout=args.readout,
        scenario=args.scenario,
    )

    # ------------------------------------------------------------------
    # Structural ensemble
    # ------------------------------------------------------------------

    labels = list(
        STRUCTURAL_DG_KCAL_MOL.keys()
    )

    all_dg = np.array(
        list(
            STRUCTURAL_DG_KCAL_MOL.values()
        ),
        dtype=float,
    )

    if len(all_dg) == 0:
        raise RuntimeError(
            "STRUCTURAL_DG_KCAL_MOL is empty."
        )

    print("=" * 72)
    print("STRUCTURE-DERIVED Kd ESTIMATES")
    print("=" * 72)

    for label in labels:

        dg = (
            STRUCTURAL_DG_KCAL_MOL[label]
        )

        kd = float(
            dg_to_kd_nM(dg)
        )

        print(
            f"{label:<42} "
            f"ΔG={dg:>6.2f} kcal/mol   "
            f"Kd={kd:>8.3f} nM"
        )

    central_dg = float(
        np.mean(all_dg)
    )

    central_kd = float(
        dg_to_kd_nM(central_dg)
    )

    print()

    print(
        "Geometric-central structural Kd: "
        f"{central_kd:.3f} nM"
    )

    # ------------------------------------------------------------------
    # Monte Carlo sampling
    # ------------------------------------------------------------------

    # Sample one of the experimentally represented dimer interfaces
    # with equal probability.
    interface_index = rng.integers(
        0,
        len(all_dg),
        size=args.n,
    )

    dg_base = all_dg[
        interface_index
    ]

    # Propagate PRODIGY calibration uncertainty in ΔG space.
    dg_noise = rng.normal(
        loc=0.0,
        scale=args.sigma,
        size=args.n,
    )

    dg_samples = (
        dg_base
        +
        dg_noise
    )

    kd_samples = dg_to_kd_nM(
        dg_samples
    )

    kd_quantiles = np.percentile(
        kd_samples,
        [5, 25, 50, 75, 95],
    )

    print()

    print(
        f"Monte Carlo Kd distribution "
        f"(sigma={args.sigma} kcal/mol, "
        f"N={args.n}):"
    )

    print(
        f"5%={kd_quantiles[0]:.3f}  "
        f"25%={kd_quantiles[1]:.3f}  "
        f"median={kd_quantiles[2]:.3f}  "
        f"75%={kd_quantiles[3]:.3f}  "
        f"95%={kd_quantiles[4]:.3f} nM"
    )

    # ------------------------------------------------------------------
    # Determine common deterministic simulation range
    # ------------------------------------------------------------------

    grid_min = max(
        curves["ox"][0].min(),
        curves["er"][0].min(),
    )

    grid_max = min(
        curves["ox"][0].max(),
        curves["er"][0].max(),
    )

    below_grid = (
        kd_samples < grid_min
    )

    above_grid = (
        kd_samples > grid_max
    )

    outside_grid = (
        below_grid
        |
        above_grid
    )

    p_below_grid = float(
        below_grid.mean()
    )

    p_above_grid = float(
        above_grid.mean()
    )

    p_outside_grid = float(
        outside_grid.mean()
    )

    print()
    print("=" * 72)
    print("MONTE CARLO GRID-COVERAGE CHECK")
    print("=" * 72)

    print(
        f"Deterministic Kd grid: "
        f"{grid_min:g} – {grid_max:g} nM"
    )

    print(
        f"P(Kd below grid) = "
        f"{100 * p_below_grid:.4f}%"
    )

    print(
        f"P(Kd above grid) = "
        f"{100 * p_above_grid:.4f}%"
    )

    print(
        f"P(Kd outside grid) = "
        f"{100 * p_outside_grid:.4f}%"
    )

    if p_outside_grid > 0:

        print()
        print(
            "NOTE: Samples outside the deterministic grid are "
            "not used for probability estimates below."
        )

        print(
            "This avoids silently assigning edge-response values "
            "to structurally sampled Kd values outside the "
            "simulated domain."
        )

    # ------------------------------------------------------------------
    # Restrict probability calculation to the simulated Kd domain
    # ------------------------------------------------------------------

    in_grid = ~outside_grid

    kd_in_grid = kd_samples[
        in_grid
    ]

    n_in_grid = int(
        in_grid.sum()
    )

    if n_in_grid == 0:
        raise RuntimeError(
            "No Monte Carlo samples fall inside the "
            "deterministic Kd grid."
        )

    coverage_fraction = (
        n_in_grid
        /
        args.n
    )

    print()

    print(
        f"Samples used for response propagation: "
        f"{n_in_grid}/{args.n} "
        f"({100 * coverage_fraction:.4f}%)"
    )

    # ------------------------------------------------------------------
    # Functional deterministic intervals
    # ------------------------------------------------------------------

    print()
    print("=" * 72)
    print("DETERMINISTIC FUNCTIONAL Kd INTERVALS")
    print("=" * 72)

    functional_intervals = {}

    for variant in ("ox", "er"):

        (
            kd_grid,
            fold_grid,
            ratio_grid,
        ) = curves[variant]

        intervals = find_functional_intervals(
            kd_grid,
            fold_grid,
            ratio_grid,
            args.fold,
            args.ratio,
        )

        functional_intervals[
            variant
        ] = intervals

        print()
        print(variant.upper())

        if not intervals:

            print(
                "No functional Kd interval found "
                "within the simulated grid."
            )

        else:

            for index, (
                lower,
                upper,
            ) in enumerate(
                intervals,
                start=1,
            ):

                print(
                    f"interval {index}: "
                    f"{format_interval(lower, upper, kd_grid.min(), kd_grid.max())}"
                )

    # ------------------------------------------------------------------
    # Propagation through circuit response
    # ------------------------------------------------------------------

    print()
    print("=" * 72)
    print(
        "PROPAGATION THROUGH CIRCUIT RESPONSE"
    )

    print(
        f"scenario={args.scenario}, "
        f"fold>={args.fold}, "
        f"ratio<={args.ratio}"
    )

    print("=" * 72)

    summary = []
    both_masks = {}

    for variant in ("ox", "er"):

        (
            kd_grid,
            fold_grid,
            ratio_grid,
        ) = curves[variant]

        fold = interp_log(
            kd_in_grid,
            kd_grid,
            fold_grid,
        )

        ratio = interp_log(
            kd_in_grid,
            kd_grid,
            ratio_grid,
        )

        detectable = (
            fold >= args.fold
        )

        timer_ok = (
            ratio <= args.ratio
        )

        both = (
            detectable
            &
            timer_ok
        )

        both_masks[variant] = both

        fold_q = np.percentile(
            fold,
            [5, 50, 95],
        )

        ratio_q = np.percentile(
            ratio,
            [5, 50, 95],
        )

        p_detect = float(
            detectable.mean()
        )

        p_timer = float(
            timer_ok.mean()
        )

        p_both_conditional = float(
            both.mean()
        )

        # Probability relative to the complete structural Monte Carlo
        # ensemble. Samples outside the deterministic simulation domain
        # are treated as unresolved rather than silently extrapolated.
        p_both_resolved_mass = (
            both.sum()
            /
            args.n
        )

        print()
        print(variant.upper())

        print(
            "fold-change: "
            f"median={fold_q[1]:.4f}, "
            f"[5%,95%]="
            f"[{fold_q[0]:.4f}, "
            f"{fold_q[2]:.4f}]"
        )

        print(
            "ratio_spread: "
            f"median={ratio_q[1]:.5f}, "
            f"[5%,95%]="
            f"[{ratio_q[0]:.5f}, "
            f"{ratio_q[2]:.5f}]"
        )

        print(
            f"P(detectable | in grid) = "
            f"{100 * p_detect:.2f}%"
        )

        print(
            f"P(timer OK | in grid)   = "
            f"{100 * p_timer:.2f}%"
        )

        print(
            f"P(BOTH | in grid)       = "
            f"{100 * p_both_conditional:.2f}%"
        )

        print(
            f"Resolved functional mass "
            f"(all MC samples) = "
            f"{100 * p_both_resolved_mass:.2f}%"
        )

        summary.append({
            "variant": variant,
            "scenario": args.scenario,
            "readout": args.readout,
            "fold_threshold": args.fold,
            "ratio_threshold": args.ratio,
            "sigma_kcal": args.sigma,
            "n_samples": args.n,
            "n_in_grid": n_in_grid,
            "grid_coverage_fraction": coverage_fraction,
            "P_below_grid": p_below_grid,
            "P_above_grid": p_above_grid,
            "P_outside_grid": p_outside_grid,

            "kd_p05": kd_quantiles[0],
            "kd_p25": kd_quantiles[1],
            "kd_median": kd_quantiles[2],
            "kd_p75": kd_quantiles[3],
            "kd_p95": kd_quantiles[4],

            "fold_p05_in_grid": fold_q[0],
            "fold_median_in_grid": fold_q[1],
            "fold_p95_in_grid": fold_q[2],

            "ratio_p05_in_grid": ratio_q[0],
            "ratio_median_in_grid": ratio_q[1],
            "ratio_p95_in_grid": ratio_q[2],

            "P_detect_given_in_grid": p_detect,
            "P_timer_given_in_grid": p_timer,
            "P_both_given_in_grid": p_both_conditional,
            "resolved_functional_mass": p_both_resolved_mass,
        })

    # ------------------------------------------------------------------
    # Joint ER + OX functionality
    # ------------------------------------------------------------------

    joint = (
        both_masks["ox"]
        &
        both_masks["er"]
    )

    p_joint_conditional = float(
        joint.mean()
    )

    p_joint_resolved_mass = (
        joint.sum()
        /
        args.n
    )

    print()
    print("=" * 72)
    print(
        "JOINT FUNCTIONALITY "
        "(same sampled Kd for OX and ER)"
    )
    print("=" * 72)

    print(
        f"P(fully functional | in grid) = "
        f"{100 * p_joint_conditional:.2f}%"
    )

    print(
        f"Resolved joint functional mass "
        f"(all MC samples) = "
        f"{100 * p_joint_resolved_mass:.2f}%"
    )

    print(
        f"Unresolved structural mass outside grid = "
        f"{100 * p_outside_grid:.4f}%"
    )

    summary.append({
        "variant": "joint",
        "scenario": args.scenario,
        "readout": args.readout,
        "fold_threshold": args.fold,
        "ratio_threshold": args.ratio,
        "sigma_kcal": args.sigma,
        "n_samples": args.n,
        "n_in_grid": n_in_grid,
        "grid_coverage_fraction": coverage_fraction,
        "P_below_grid": p_below_grid,
        "P_above_grid": p_above_grid,
        "P_outside_grid": p_outside_grid,

        "kd_p05": kd_quantiles[0],
        "kd_p25": kd_quantiles[1],
        "kd_median": kd_quantiles[2],
        "kd_p75": kd_quantiles[3],
        "kd_p95": kd_quantiles[4],

        "P_both_given_in_grid": p_joint_conditional,
        "resolved_functional_mass": p_joint_resolved_mass,
    })

    # ------------------------------------------------------------------
    # Interpret structural median relative to functional intervals
    # ------------------------------------------------------------------

    median_kd = float(
        np.median(kd_samples)
    )

    print()
    print("=" * 72)
    print(
        "STRUCTURAL MEDIAN VS FUNCTIONAL WINDOWS"
    )
    print("=" * 72)

    print(
        f"Median structural Kd = "
        f"{median_kd:.3f} nM"
    )

    for variant in ("ox", "er"):

        intervals = functional_intervals[
            variant
        ]

        inside_any = any(
            lower <= median_kd <= upper
            for lower, upper in intervals
        )

        print()

        print(
            f"{variant.upper()}: "
            f"median structural Kd is "
            f"{'INSIDE' if inside_any else 'OUTSIDE'} "
            f"the deterministic functional interval."
        )

        if intervals:

            for lower, upper in intervals:

                print(
                    "  functional interval: "
                    f"{lower:.3f} – "
                    f"{upper:.3f} nM"
                )

    # ------------------------------------------------------------------
    # Output
    # ------------------------------------------------------------------

    keys = sorted(
        {
            key
            for row in summary
            for key in row
        }
    )

    os.makedirs(
        os.path.dirname(OUT_CSV),
        exist_ok=True,
    )

    with open(
        OUT_CSV,
        "w",
        newline="",
        encoding="utf-8",
    ) as fh:

        writer = csv.DictWriter(
            fh,
            fieldnames=keys,
        )

        writer.writeheader()

        writer.writerows(
            summary
        )

    print()

    print(
        f"Wrote "
        f"{os.path.normpath(OUT_CSV)}"
    )


if __name__ == "__main__":
    main()

    